name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "First command"
          echo "Hello Gandhi"
      - name: Print goodby
        run:  |
          echo "Done - bye"
          echo "Second command"
      
