name: First Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependecies
        run: npm ci
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "First command"
          echo "Hello Gandhi"
      - name: Print goodby
        run:  |
          echo "Done - bye"
          echo "Second command"